**What is Numpy?**
A numpy array is similar to a list. It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing numpy:

In [1]:
# import numpy library

import numpy as np 

In [2]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [3]:
# Each element is of the same type, in this case integers
# As with lists, we can access each element via a square bracket:

# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


Type
If we check the type of the array we get numpy.ndarray:

In [4]:
# Check the type of the array

type(a)

numpy.ndarray

As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the Data-type of the array’s elements. In this case a 64-bit integer:

In [5]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int32')

We can create a numpy array with real numbers:

In [7]:
# Create a numpy array

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
b

array([  3.1 ,  11.02,   6.2 , 213.2 ,   5.2 ])

When we check the type of the array we get numpy.ndarray:

In [8]:
# Check the type of array

type(b)

numpy.ndarray

In [9]:
# Check the value type

b.dtype

dtype('float64')

**Assign value**
We can change the value of the array, consider the array c:

In [10]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [11]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [12]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

***Slicing***
Like lists, we can slice the numpy array, and we can select the elements from 1 to 3 and assign it to a new numpy array d as follows:

In [13]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [14]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

***Assign Value with List***
Similarly, we can use a list to select a specific index. The list ' select ' contains several values:

In [16]:
# Create the index list

select = [0, 2, 3]
select 


[0, 2, 3]

In [17]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300])

In [18]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

***Other Attributes***
Let's review some basic array attributes using the array a:

In [19]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [20]:
# Get the size of numpy array

a.size

5

The next two attributes will make more sense when we get to higher dimensions but let's review them. The attribute ndim represents the number of array dimensions or the rank of the array, in this case, one

In [21]:
# Get the number of dimensions of numpy array

a.ndim

1

The attribute shape is a tuple of integers indicating the size of the array in each dimension:

In [22]:
# Get the shape/size of numpy array

a.shape

(5,)

In [23]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [24]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [25]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [26]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [27]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [ ]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

***Numpy Array Operations***

Array Addition
Consider the numpy array u:

In [29]:
u = np.array([1,0])
u

array([1, 0])

In [30]:
v = np.array([0,1])
v

array([0, 1])

In [31]:
# Numpy Array Addition
z = u+v
z

array([1, 1])

In [32]:
# The operation is equivalent to vector addition:
# Plot numpy arrays

Plotvec1(u, z, v)

NameError: name 'Plotvec1' is not defined

***Array Multiplication***

In [33]:
# Create a numpy array

y = np.array([1, 2])
y

array([1, 2])

In [34]:
# Numpy Array Multiplication

z = 2 * y
z

# This is equivalent to multiplying a vector by a scaler

array([2, 4])

***Product of Two Numpy Arrays***

In [35]:
# Create a numpy array

u = np.array([1, 2])
u

array([1, 2])

In [36]:
# Create a numpy array

v = np.array([3, 2])
v

array([3, 2])

In [37]:
# Calculate the production of two numpy arrays

z = u * v
z

array([3, 4])

***Dot Product***

In [38]:
# Calculate the dot product

np.dot(u, v)

7

***Adding Constant to a Numpy Array***

In [39]:
# Create a constant to numpy array

u = np.array([1, 2, 3, -1]) 
u


array([ 1,  2,  3, -1])

In [40]:
# Add the constant to array

u + 1

array([2, 3, 4, 0])

***Mathematical Functions***

In [41]:
# The value of pi

np.pi

3.141592653589793

In [43]:
# Create the numpy array in radians

x = np.array([0, np.pi/2 , np.pi])
x

array([0.        , 1.57079633, 3.14159265])

In [44]:
# We can apply the function sin to 
# the array x and assign the values to the array y; this applies the sine function to each element in the array:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

***Linspace***
A useful function for plotting mathematical functions is linspace. Linspace returns evenly spaced numbers over a specified interval. We specify the starting point of the sequence and the ending point of the sequence. The parameter "num" indicates the Number of samples to generate, in this case 5:

In [54]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

In [55]:
# Makeup a numpy array within [-2, 2] and 9 elements

np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [56]:
# Makeup a numpy array within [0, 2π] and 100 elements 

x = np.linspace(0, 2*np.pi, num=100)

In [57]:
# Calculate the sine of x list

y = np.sin(x)

In [58]:
# Plot the result

plt.plot(x, y)

NameError: name 'plt' is not defined

***Quiz on 1D Numpy Array***

Implement the following vector subtraction in numpy: u-v

In [59]:
# Write your code below and press Shift+Enter to execute

u = np.array([1, 0])
v = np.array([0, 1])

In [60]:
z=u - v
z

array([ 1, -1])

Multiply the numpy array z with -2:

In [61]:
# Write your code below and press Shift+Enter to execute

z = np.array([2, 4])

In [63]:
q = z*-2
q

array([-4, -8])

Consider the list [1, 2, 3, 4, 5] and [1, 0, 1, 0, 1], and cast both lists to a numpy array then multiply them together:

In [64]:
a = np.array([1,2,3,4,5])
b = np.array([1,0,1,0,1])
d = a*b
d


array([1, 0, 3, 0, 5])

Convert the list [-1, 1] and [1, 1] to numpy arrays a and b. Then, plot the arrays as vectors using the fuction Plotvec2 and find the dot product:

In [65]:
a = np.array([-1,1])
b = np.array([1,1])
Plotvec2(a, b)
print("The dot product is", np.dot(a,b))

NameError: name 'Plotvec2' is not defined

Why are the results of the dot product for [-1, 1] and [1, 1] and the dot product for [1, 0] and [0, 1] zero, but not zero for the dot product for [1, 1] and [0, 1]?

Hint: Study the corresponding figures, pay attention to the direction the arrows are pointing to.