***Create a 2D Numpy Array***

In [61]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [62]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
# We can use the attribute ndim to obtain the number of axes or dimensions referred to as the rank
# Show the numpy array dimensions

A.ndim

2

In [5]:
# Attribute shape returns a tuple corresponding to the size or number of each dimension
# Show the numpy array shape

A.shape

(3, 3)

In [6]:
# The total number of elements in the array is given by the attribute size
# Show the numpy array size

A.size

9

***Accessing different elements of a Numpy Array***
We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:

In [7]:
# Access the element on the second row and third column

A[1, 2]

23

In [8]:
# Access the element on the second row and third column

A[1][2]

23

In [9]:
# Access the element on the first row and first column

A[0][0]

11

In [10]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [11]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

***Basic Operations***
We can also add arrays. The process is identical to matrix addition. Matrix addition of X and Y is shown in the following figure:

In [12]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X


array([[1, 0],
       [0, 1]])

In [13]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [14]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix Y by the scaler 2, we simply multiply every element in the matrix by 2 as shown in the figure.

In [15]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [16]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or Hadamard product. Consider matrix X and Y. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix Y or X, as shown in the following figure.

In [17]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [19]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the numpy arrays A and B as follows:

In [20]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [21]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function dot to multiply the arrays together

In [22]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [23]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [ ]:
We use the numpy attribute T to calculate the transposed matrix

In [24]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [25]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

***Quiz on 2D Numpy Array***

Consider the following list a, convert it to Numpy Array
Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [47]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Calculate the numpy array size

In [48]:
A.size

12

Access the element on the first row and first and second columns

In [49]:
A[0][0:2]

array([1, 2])

Perform matrix multiplication with the numpy arrays A and B

In [50]:
B = np.array([[0, 1, 1], [1, 0, 1]])
B

array([[0, 1, 1],
       [1, 0, 1]])

In [51]:
x = np.dot(A,B)
x

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

In [63]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])

In [64]:
Z=np.dot(X,Y)

In [66]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y

In [67]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [70]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)